azs:
- name: z1

vm_types:
- name: small

disk_types:
- name: default
  disk_size: 1024

compilation:
  workers: 5
  az: z1
  reuse_compilation_vms: true
  vm_type: small
  network: default

networks:
- name: default
  type: manual
  subnets:
  - range: 10.244.1.0/24
    azs: [z1]
    reserved: [10.244.1.1]
    static: [10.244.1.2, 10.244.1.6, 10.244.1.10, 10.244.1.14, 10.244.1.18]
